### ISSUE TITLE
Further documentation please

### ISSUE THREAD

**Issue by AL89** [meshpro/dmsh#91]
Hi @nschloe 
I enjoy your work. I have been searching for solutions to create mesh'es using Python and then I came across dmsh.

Even though it is working, I could, however, use some further documentation in regards to some parameters. That is, instead of looking at the Python files itself.
Let's look at the very first segment of code. Here, there is a line: 

`X, cells = dmsh.generate(geo, 0.1)`

It is the parameter of `0.1` that I have my doubts about, which is the `target_edge_size`, right? I really could use some explanation/documentation about this. I mean, what is the "size" telling us? Is it the length of an edge? Is it the area of a triangle? What exactly?

Same goes for your other repositories, `meshio` and `optimesh`, where parameters for the latter ones are confusing. I will just write it here instead of another issue on those repos.

This line for instance:

`X, cells = optimesh.optimize_points_cells(X, cells, "CVT (full)", 1.0e-10, 100)`
- `"CVT (full)"` is the method I suppose? Is there a list in your repository for other methods? I am looking for the correct syntax.
- `1.0e-10` is the tolerance, yeah? Tolerance of what?
- `100` - this number makes me insecure? Is this the iterations when the mesh is being optimized?

IMO, the explanation doesn't have to be long - but just think about it, when you are developing your hard work :)

**Comment by nschloe** [comment]
Thanks for the suggestions. I've renamed `target_edge_size` to `target_edge_length` which hopefully makes things clear. I'll take care about the other things when I think about it.
