### ISSUE TITLE
Anaconda - dmsh installation problem

### ISSUE THREAD

**Issue by griff10000** [meshpro/dmsh#93]
I have a new machine with Windows 11 and have installed Anaconda3-2021.11-Windows-x86_64.

Tried running in powershell window:
   `conda install dmsh` 
Not found.

Tried:
  `pip install dmsh`
This installed dmsh.

But get following error when running a simple dmsh application that ran on my old Windows 10 machine:

`ImportError: cannot import name 'NDArray' from 'numpy.typing' (C:\Users\Graham\anaconda3\lib\site-packages\numpy\typing\__init__.py)`

The installed numpy version = 1.20.3

**Comment by matael** [comment]
I second that, some of my students had the issue during a practical and I ended up generating the mesh on my machine and sending them the arrays.

Windows 10, anaconda and numpy 1.20.X
