### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by whiffee** [meshpro/dmsh#96]
Working with Python 3.9.13, on Windows, from within Jupyter, I ran:

!pip3 install dmsh

. . . 

. . .

Collecting dmsh
  Using cached dmsh-0.2.21-py3-none-any.whl (164 kB)
  Using cached dmsh-0.2.20-py3-none-any.whl (164 kB)

The conflict is caused by:
    dmsh 0.2.23 depends on meshplex<0.19.0 and >=0.16.0
    dmsh 0.2.22 depends on meshplex<0.19.0 and >=0.16.0
    dmsh 0.2.21 depends on meshplex<0.19.0 and >=0.16.0
    dmsh 0.2.20 depends on meshplex<0.19.0 and >=0.16.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

And then I ran

!pip3 index versions meshplex

meshplex (0.19.1)
Available versions: 0.19.1

I don't know how to handle this. Can you advise?

thanks
Gary Bollenbach

**Comment by nschloe** [comment]
Fixed now.
